"""Add preview_data to bookmark

Revision ID: c714106dbdc3
Revises: 30dc880d18fa
Create Date: 2024-05-05 21:53:10.995224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c714106dbdc3'
down_revision = '30dc880d18fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_data', sa.JSON(), nullable=False))
        batch_op.alter_column('folder_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.alter_column('folder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('preview_data')

    # ### end Alembic commands ###
